"use client";

import { useEffect, useState } from "react";
import { noteApi, Note } from "@/lib/api";
import { NoteCard } from "@/components/NoteCard";
import { CreateNoteDialog } from "@/components/CreateNoteDialog";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { Skeleton } from "@/components/ui/skeleton";
import { Search, PenTool, Sparkles } from "lucide-react";
import { Input } from "@/components/ui/input";

export default function Home() {
  const [notes, setNotes] = useState<Note[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [summarizingId, setSummarizingId] = useState<string | null>(null);

  useEffect(() => {
    fetchNotes();
  }, []);

  const fetchNotes = async () => {
    try {
      setLoading(true);
      const data = await noteApi.getAll();
      setNotes(data);
    } catch (error) {
      toast.error("Failed to load notes. Is the backend running?");
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = async (title: string, content: string) => {
    try {
      const newNote = await noteApi.create(title, content);
      setNotes([newNote, ...notes]);
      toast.success("Note created with AI summary!");
    } catch (error) {
      toast.error("Failed to create note.");
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await noteApi.delete(id);
      setNotes(notes.filter((n) => n.id !== id));
      toast.success("Note deleted successfully.");
    } catch (error) {
      toast.error("Failed to delete note.");
    }
  };

  const handleSummarize = async (id: string) => {
    try {
      setSummarizingId(id);
      const updatedNote = await noteApi.summarize(id);
      setNotes(notes.map((n) => (n.id === id ? updatedNote : n)));
      toast.success("Summary generated by Gemini.");
    } catch (error) {
      toast.error("AI Summarization failed.");
    } finally {
      setSummarizingId(null);
    }
  };

  const filteredNotes = notes.filter(
    (n) =>
      n.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      n.content.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <main className="min-h-screen bg-background selection:bg-primary/20">
      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b bg-background/80 backdrop-blur-xl">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="h-9 w-9 bg-primary flex items-center justify-center rounded-xl shadow-lg shadow-primary/20">
              <PenTool className="h-5 w-5 text-primary-foreground" />
            </div>
            <h1 className="text-xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/60">
              AI Note Summarizer
            </h1>
          </div>

          <div className="flex items-center gap-4">
            <div className="relative hidden sm:block">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search notes..."
                className="pl-9 w-64 bg-secondary/50 border-none focus-visible:ring-primary/20 h-9 transition-all"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 mb-12">
          <div className="space-y-1">
            <h2 className="text-3xl font-extrabold tracking-tight">Your Digital Brain</h2>
            <p className="text-muted-foreground">
              Collect thoughts and get instant summaries powered by Gemini AI.
            </p>
          </div>
          <CreateNoteDialog onCreate={handleCreate} />
        </div>

        {/* Notes Grid */}
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3].map((i) => (
              <div key={i} className="space-y-4 p-6 border rounded-xl">
                <Skeleton className="h-6 w-3/4 rounded-lg" />
                <Skeleton className="h-24 w-full rounded-lg" />
                <div className="flex justify-end">
                  <Skeleton className="h-8 w-24 rounded-lg" />
                </div>
              </div>
            ))}
          </div>
        ) : filteredNotes.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {filteredNotes.map((note) => (
              <NoteCard
                key={note.id}
                note={note}
                onDelete={handleDelete}
                onSummarize={handleSummarize}
                isSummarizing={summarizingId === note.id}
              />
            ))}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-20 text-center space-y-4 border-2 border-dashed rounded-3xl border-primary/10">
            <div className="h-16 w-16 bg-primary/5 rounded-full flex items-center justify-center border border-dashed border-primary/20">
              <Sparkles className="h-8 w-8 text-primary/40" />
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-semibold">No notes yet</h3>
              <p className="text-muted-foreground max-w-sm mx-auto">
                Start your journey by capturing your first note. Our AI is ready to help you summarize it.
              </p>
            </div>
          </div>
        )}
      </div>

      <Toaster richColors position="top-right" />
    </main>
  );
}
